### ISSUE TITLE
Something is wrong with the weight's edjustment

### ISSUE THREAD

**Issue by NTHieu95** [CS-ZSC/CharRecognition#1]
I fixed your code a little bit, but not the weights parts. And it turns out when using 'test', the only answer is the latest folder of character it learned (for example, the network learned folder 'H' at the end of the loop and the test result  is always 'H').

**Comment by kirononame** [comment]
The learning set that is used to learn from is too small but the results get better when it learn from the same data many times I make it around **100** times but still the success rate is very low. You might see better results by making it learn more times than I used and you can change the learning rate i used **.001** which is very low but I wanted to see less impact from each learning but you can increase it and test but don't increase it too much so it won't overshoot. These results are from the updated code I just added, you can now tell the network to draw lowercase letter to see how the network see the character should look like after it learnt, for me i tested **a , c** which looked the same and can not be recognized and also **f** which can be recognized. The characters results are in **testing_results** folder.

**Comment by NTHieu95** [comment]
Thank you so much for the respond and update. Now I know the problem is my epoch was just too low. And the dataset is not quite good. You can remove the whole white space by some simple opencv tricks to get a nicer dataset. 
I asked just to make sure that your network works correctly or not.
